import java.awt.Color;
import javax.swing.JFrame;
import java.util.regex.Pattern;
import java.util.Random;
import java.util.regex.Matcher;

/**
 *
 * @author Syasal
 */


public class RegisterForm extends javax.swing.JFrame {
    Random r = new Random(); //random
    String fn=""; //fullname
    String ps =null; //password
    String letters = "abcdefghjkmnpqrstuvwxyzABCDEFGHJKMNPQRSTUVWXYZ0123456789@._"; //huruf,angka, dan @ 
    String id=""; //email
    String pass1=""; //password
    static String FN[] = new String [100]; // array untuk fullname
    static String pass[] = new String [100]; // array password
    static String email[] = new String[100]; // array email
    

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Pass = new javax.swing.JTextField();
        jButton_Reset1 = new javax.swing.JButton();
        jButton_login = new javax.swing.JButton();
        validateLogin = new javax.swing.JLabel();
        jTextField_Email1 = new javax.swing.JTextField();
        jLabelClose2 = new javax.swing.JLabel();
        jLabelMin1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelRegister = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();
        jLabel_Email = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_FN = new javax.swing.JLabel();
        jTextField_FN = new javax.swing.JTextField();
        jButtonGen = new javax.swing.JButton();
        jButton_Reset = new javax.swing.JButton();
        jButtonRegister = new javax.swing.JButton();
        EmailRec = new javax.swing.JLabel();
        jLabelRVEmail = new javax.swing.JLabel();
        ValidateAccount = new javax.swing.JLabel();
        jLabelClose1 = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabel_sign = new javax.swing.JLabel();
        jLabel_pass2 = new javax.swing.JLabel();
        jTextField_Email2 = new javax.swing.JTextField();
        jLabel_passgen = new javax.swing.JLabel();
        Background1 = new javax.swing.JPanel();
        jLabel_Email1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_FN1 = new javax.swing.JLabel();
        jTextField_Pass1 = new javax.swing.JTextField();
        jButtonGen1 = new javax.swing.JButton();
        jButton_Reset2 = new javax.swing.JButton();
        jButtonUbah = new javax.swing.JButton();
        ValidateAccount1 = new javax.swing.JLabel();
        jLabelClose3 = new javax.swing.JLabel();
        jLabelMin2 = new javax.swing.JLabel();
        jLabel_sign1 = new javax.swing.JLabel();
        jLabel_passgen1 = new javax.swing.JTextField();
        jLabel_pass3 = new javax.swing.JLabel();
        jTextField_Email3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jTabbedPane2.setBackground(new java.awt.Color(241, 169, 160));
        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(25, 181, 254));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel4.setText("Password  :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel5.setText("Email        : ");

        jTextField_Pass.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PassActionPerformed(evt);
            }
        });

        jButton_Reset1.setBackground(new java.awt.Color(192, 47, 53));
        jButton_Reset1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton_Reset1.setText("RESET");
        jButton_Reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Reset1ActionPerformed(evt);
            }
        });

        jButton_login.setBackground(new java.awt.Color(248, 148, 6));
        jButton_login.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton_login.setText("LOGIN");
        jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginActionPerformed(evt);
            }
        });

        validateLogin.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N

        jTextField_Email1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_Email1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Email1ActionPerformed(evt);
            }
        });

        jLabelClose2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelClose2.setText("x");
        jLabelClose2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClose2MouseClicked(evt);
            }
        });

        jLabelMin1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelMin1.setText("-");
        jLabelMin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMin1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Belum mempunyai akses ?");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Click");

        jLabelRegister.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelRegister.setText("Sign Up");
        jLabelRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegisterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButton_Reset1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_login, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Email1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(jTextField_Pass))
                        .addGap(62, 62, 62)))
                .addGap(96, 96, 96))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelRegister)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(380, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelMin1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelClose2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(validateLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(245, 245, 245))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClose2)
                    .addComponent(jLabelMin1))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Email1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Reset1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_login))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validateLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelRegister))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("SIGN IN", jPanel1);

        Background.setBackground(new java.awt.Color(25, 181, 254));

        jLabel_Email.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel_Email.setText("Email      : ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("REGISTRATION");

        jLabel_FN.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel_FN.setText("Username :");

        jTextField_FN.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jButtonGen.setBackground(new java.awt.Color(34, 49, 63));
        jButtonGen.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButtonGen.setText("Generate");
        jButtonGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenActionPerformed(evt);
            }
        });

        jButton_Reset.setBackground(new java.awt.Color(192, 47, 53));
        jButton_Reset.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton_Reset.setText("Reset");
        jButton_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ResetActionPerformed(evt);
            }
        });

        jButtonRegister.setBackground(new java.awt.Color(248, 148, 6));
        jButtonRegister.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButtonRegister.setText("Register");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });

        EmailRec.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N

        jLabelRVEmail.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N

        ValidateAccount.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N

        jLabelClose1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelClose1.setText("x");
        jLabelClose1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClose1MouseClicked(evt);
            }
        });

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        jLabel_sign.setText("SIGN IN");
        jLabel_sign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_signMouseClicked(evt);
            }
        });

        jLabel_pass2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel_pass2.setText("Password :");

        jTextField_Email2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel_passgen.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addComponent(jLabel_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelRVEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BackgroundLayout.createSequentialGroup()
                                        .addGap(174, 174, 174)
                                        .addComponent(jLabel1))
                                    .addGroup(BackgroundLayout.createSequentialGroup()
                                        .addComponent(jLabel_FN, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField_FN, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(BackgroundLayout.createSequentialGroup()
                                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(BackgroundLayout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(jButton_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel_sign)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonRegister))
                                            .addGroup(BackgroundLayout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(jLabel_passgen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonGen)))
                                        .addGap(18, 18, 18)
                                        .addComponent(ValidateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 13, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelClose1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EmailRec, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundLayout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jLabel_pass2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(690, Short.MAX_VALUE)))
            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundLayout.createSequentialGroup()
                    .addGap(244, 244, 244)
                    .addComponent(jTextField_Email2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(318, Short.MAX_VALUE)))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelClose1)
                        .addComponent(jLabelMin)))
                .addGap(22, 22, 22)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_FN)
                    .addComponent(jTextField_FN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRVEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Email))
                .addGap(18, 18, 18)
                .addComponent(EmailRec, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValidateAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_passgen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRegister)
                    .addComponent(jLabel_sign))
                .addGap(54, 54, 54))
            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                    .addContainerGap(224, Short.MAX_VALUE)
                    .addComponent(jLabel_pass2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(144, 144, 144)))
            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundLayout.createSequentialGroup()
                    .addGap(146, 146, 146)
                    .addComponent(jTextField_Email2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(226, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("SIGN UP", Background);

        Background1.setBackground(new java.awt.Color(25, 181, 254));

        jLabel_Email1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel_Email1.setText("Password Lama      : ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("UBAH PASSWORD");

        jLabel_FN1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel_FN1.setText("Email      :");

        jTextField_Pass1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jButtonGen1.setBackground(new java.awt.Color(34, 49, 63));
        jButtonGen1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButtonGen1.setText("Generate");
        jButtonGen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGen1ActionPerformed(evt);
            }
        });

        jButton_Reset2.setBackground(new java.awt.Color(192, 47, 53));
        jButton_Reset2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton_Reset2.setText("Reset");
        jButton_Reset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Reset2ActionPerformed(evt);
            }
        });

        jButtonUbah.setBackground(new java.awt.Color(248, 148, 6));
        jButtonUbah.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButtonUbah.setText("Ubah");
        jButtonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUbahActionPerformed(evt);
            }
        });

        ValidateAccount1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N

        jLabelClose3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelClose3.setText("x");
        jLabelClose3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClose3MouseClicked(evt);
            }
        });

        jLabelMin2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelMin2.setText("-");
        jLabelMin2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMin2MouseClicked(evt);
            }
        });

        jLabel_sign1.setText("SIGN IN");
        jLabel_sign1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_sign1MouseClicked(evt);
            }
        });

        jLabel_passgen1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel_pass3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel_pass3.setText("Password Baru :");

        jTextField_Email3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        javax.swing.GroupLayout Background1Layout = new javax.swing.GroupLayout(Background1);
        Background1.setLayout(Background1Layout);
        Background1Layout.setHorizontalGroup(
            Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background1Layout.createSequentialGroup()
                .addGroup(Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Background1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel_Email1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelMin2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelClose3))
                    .addGroup(Background1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Background1Layout.createSequentialGroup()
                                .addGroup(Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Background1Layout.createSequentialGroup()
                                        .addComponent(jButton_Reset2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel_sign1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField_Pass1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(Background1Layout.createSequentialGroup()
                                                .addGap(174, 174, 174)
                                                .addComponent(jLabel6))
                                            .addGroup(Background1Layout.createSequentialGroup()
                                                .addComponent(jLabel_FN1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField_Email3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Background1Layout.createSequentialGroup()
                                .addGap(0, 113, Short.MAX_VALUE)
                                .addGroup(Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Background1Layout.createSequentialGroup()
                                        .addComponent(jLabel_passgen1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonGen1)
                                        .addGap(185, 185, 185))
                                    .addComponent(ValidateAccount1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addGroup(Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Background1Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jLabel_pass3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(612, Short.MAX_VALUE)))
        );
        Background1Layout.setVerticalGroup(
            Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background1Layout.createSequentialGroup()
                .addGroup(Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelClose3)
                        .addComponent(jLabelMin2)))
                .addGap(22, 22, 22)
                .addGroup(Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_FN1)
                    .addComponent(jTextField_Email3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Email1)
                    .addComponent(jTextField_Pass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGen1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_passgen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ValidateAccount1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Reset2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUbah)
                    .addComponent(jLabel_sign1))
                .addGap(54, 54, 54))
            .addGroup(Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Background1Layout.createSequentialGroup()
                    .addContainerGap(237, Short.MAX_VALUE)
                    .addComponent(jLabel_pass3)
                    .addGap(144, 144, 144)))
        );

        jTabbedPane2.addTab("CHANGE PASSWORD", Background1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane2MouseClicked

    private void jLabel_signMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_signMouseClicked
        LoginForm lf = new LoginForm();
        lf.setVisible(true);
        lf.pack();
        lf.setLocationRelativeTo(null);
        lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel_signMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClose1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelClose1MouseClicked

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        // Email Regex
        Pattern pMail = Pattern.compile("^([A-Za-z][A-Za-z0-9\\-\\.\\_]*)\\@([A-Za-z][A-Za-z0-9\\-\\_]*)(\\.[A-Za-z][A-Za-z0-9\\-\\_]*)+$"); //saat register email harus memakai @gmail.com
        Matcher mMail = pMail.matcher(jTextField_Email2.getText()); // matcher = menyesuaiakan email untuk sesuai
        boolean isEmailValid = mMail.matches();
        if(isEmailValid){ // saat email valid maka d// ia berwarna biru dan dia akan di nyatakan email valid
            jLabelRVEmail.setText("Valid Email");
            jLabelRVEmail.setForeground(Color.BLUE);

        }else{ // saat email tidak valid maka dia berwarna merah dan dia akan di nyatakan email tidak valid
            jLabelRVEmail.setText("InValid Email");
            jLabelRVEmail.setForeground(Color.red);
        }

        //create account

        if (isEmailValid && ps != null){ //jika email valid password tidak boleh kosong
            fn = ""+jTextField_FN.getText(); //fullname berasal dari text field fullname
            id = ""+jTextField_Email2.getText();//id berasal dari text field email
            pass1 = ps;
            for (int i = 0; i < email.length; i++){
                if(email[i] != null){ //email akan merekomendasikan jika email sudah di gunakan
                    if(email[i].equals(id)){
                        String EmailReq = email[i];
                        int EmailRand = r.nextInt(100);
                        EmailRec.setText("We Reccomended " + EmailRand + EmailReq + "");
                        ValidateAccount.setText("Account Already Created !!");
                        jLabelRVEmail.setText("InValid Email");
                        jLabelRVEmail.setForeground(Color.red);
                        break;
                    }else{
                    }
                }else if(email[i] == null){//jika email username dan password valid maka akun terbuat
                    FN[i]=fn;
                    pass[i]=pass1;
                    email[i]= id;
                    ValidateAccount.setText("Account Created !!");
                    EmailRec.setText("");
                    break;

                }

            }

        }
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jButton_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ResetActionPerformed
        // TODO add your handling code here:
        jLabel_passgen.setText("");
        jTextField_FN.setText("");
        jTextField_Email2.setText("");
        jLabel_passgen.setText("");
        ValidateAccount.setText("");
        jLabelRVEmail.setText("");
        EmailRec.setText("");
    }//GEN-LAST:event_jButton_ResetActionPerformed

    private void jButtonGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenActionPerformed
        ps = "";
        int randomPass = r.nextInt(12 + 1 - 8) + 8;// panjang password lebih dari 8 kurang dari 12
        int rr = randomPass;
        for (int i=0; i<rr; i++) //password akan meregex di label pasword generator
        {
            int index = (int)(r.nextDouble()*letters.length());
            ps += letters.substring(index, index+1);
        }
        jLabel_passgen.setText(ps);
    }//GEN-LAST:event_jButtonGenActionPerformed

    private void jLabelRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegisterMouseClicked
        RegisterForm rgf = new RegisterForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelRegisterMouseClicked

    private void jLabelMin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMin1MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMin1MouseClicked

    private void jLabelClose2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClose2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelClose2MouseClicked

    private void jTextField_Email1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Email1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Email1ActionPerformed

    private void jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loginActionPerformed
        RegisterForm reg = new RegisterForm();
        for (int i = 0; i < 100; i++){
            if(reg.email[i] != null){ //jika email sudah di registrasi maka login sukses
                if(reg.email[i].equals(jTextField_Email1.getText()) && reg.pass[i].equals(jTextField_Pass.getText())){
                    validateLogin.setText("Login Success !");
                    break;
                } else {
                    validateLogin.setText("Login Failed !");
                }

            }else{
                validateLogin.setText("Login Failed !");

            }

        }
    }//GEN-LAST:event_jButton_loginActionPerformed

    private void jButton_Reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Reset1ActionPerformed
        // TODO add your handling code here:
        jTextField_Email1.setText("");
        jTextField_Pass.setText("");
        validateLogin.setText("");
    }//GEN-LAST:event_jButton_Reset1ActionPerformed

    private void jTextField_PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PassActionPerformed

    private void jButtonGen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGen1ActionPerformed
        ps = "";
        int randomPass = r.nextInt(12 + 1 - 8) + 8;// panjang password lebih dari 8 kurang dari 12
        int rr = randomPass;
        for (int i=0; i<rr; i++) //password akan meregex di label pasword generator
        {
            int index = (int)(r.nextDouble()*letters.length());
            ps += letters.substring(index, index+1);
        }
        jLabel_passgen1.setText(ps);
    }//GEN-LAST:event_jButtonGen1ActionPerformed

    private void jButton_Reset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Reset2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Reset2ActionPerformed

    private void jButtonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUbahActionPerformed
        // TODO add your handling code here:
        RegisterForm reg = new RegisterForm();
        for (int i = 0; i < 100; i++){
            if(reg.email[i] != null){ //jika email sudah di registrasi maka login sukses
                if(reg.email[i].equals(jTextField_Email3.getText()) && reg.pass[i].equals(jTextField_Pass1.getText())){
                    
                    ValidateAccount1.setText("Change Password Success");
                    ValidateAccount1.setForeground(Color.blue);
                    break;
                } else {
                    ValidateAccount1.setText("Change Password Failed !");
                    ValidateAccount1.setForeground(Color.red);
                }

            }else{
                ValidateAccount1.setText("Change Password Failed !");
                ValidateAccount1.setForeground(Color.red);

            }

        }
    }//GEN-LAST:event_jButtonUbahActionPerformed

    private void jLabelClose3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClose3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelClose3MouseClicked

    private void jLabelMin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMin2MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMin2MouseClicked

    private void jLabel_sign1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_sign1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_sign1MouseClicked

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Background1;
    private javax.swing.JLabel EmailRec;
    private javax.swing.JLabel ValidateAccount;
    private javax.swing.JLabel ValidateAccount1;
    private javax.swing.JButton jButtonGen;
    private javax.swing.JButton jButtonGen1;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jButtonUbah;
    private javax.swing.JButton jButton_Reset;
    private javax.swing.JButton jButton_Reset1;
    private javax.swing.JButton jButton_Reset2;
    private javax.swing.JButton jButton_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelClose1;
    private javax.swing.JLabel jLabelClose2;
    private javax.swing.JLabel jLabelClose3;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelMin1;
    private javax.swing.JLabel jLabelMin2;
    private javax.swing.JLabel jLabelRVEmail;
    private javax.swing.JLabel jLabelRegister;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_Email1;
    private javax.swing.JLabel jLabel_FN;
    private javax.swing.JLabel jLabel_FN1;
    private javax.swing.JLabel jLabel_pass2;
    private javax.swing.JLabel jLabel_pass3;
    private javax.swing.JLabel jLabel_passgen;
    private javax.swing.JTextField jLabel_passgen1;
    private javax.swing.JLabel jLabel_sign;
    private javax.swing.JLabel jLabel_sign1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField_Email1;
    private javax.swing.JTextField jTextField_Email2;
    private javax.swing.JTextField jTextField_Email3;
    private javax.swing.JTextField jTextField_FN;
    private javax.swing.JTextField jTextField_Pass;
    private javax.swing.JTextField jTextField_Pass1;
    private javax.swing.JLabel validateLogin;
    // End of variables declaration//GEN-END:variables
}
